[theme]
base = "light"
primaryColor = "#c65076"
backgroundColor = "#fff8ef"
secondaryBackgroundColor = "#fff0e5"
textColor = "#543f50"
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = false

[server]
headless = true
enableStaticServing = true
maxUploadSize = 10
